services:
  - type: web
    name: telegram-excursion-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_excursion_bot/bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 